# Generated by Django 4.2 on 2023-04-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_cliente_delete_administrador_delete_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pausas_activas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.cliente'),
        ),
    ]
